language: node_js
node_js:
  - "node"
warnings_are_errors: false
before_install:
  - npm install -g firebase-tools
install:
  - npm install
script:
  - npm run build
after_success:
  - firebase deploy --token $FIREBASE_TOKEN
branches:
  only:
    - master
